% This LilyPond file was generated by Rosegarden 13.04
\include "deutsch.ly"
\version "2.12.0"
\header {
    copyright = "Copyright (c) xxxx Die Inhaber des Copyright"
    subtitle = "Noch ohne Untertitel"
    title = "Noch ohne Titel"
    tagline = "Created using Rosegarden 13.04 and LilyPond"
}
#(set-global-staff-size 22)
#(set-default-paper-size "a4")
global = { 
    \time 4/4
    \skip 1*2 
}
globalTempo = {
    \override Score.MetronomeMark #'transparent = ##t
    \tempo 4 = 120  
}
\score {
    << % common

    \context Staff = "track 1" << 
        \set Staff.instrumentName = \markup { \center-column { " " } }
        \set Staff.midiInstrument = "Acoustic Grand Piano"
        \set Score.skipBars = ##t
        \set Staff.printKeyCancellation = ##f
        \new Voice \global
        \new Voice \globalTempo

        \context Voice = "voice 1" {
            \override Voice.TextScript #'padding = #2.0
            \override MultiMeasureRest #'expand-limit = 1
            \once \override Staff.TimeSignature #'style = #'() 
            \time 4/4
            
            \clef "treble"
            \key c \major
            a' 4 d''\rest r r  |
            r4 r d''\rest r  |
            \bar "|."
        } % Voice
    >> % Staff (final) ends

>> % notes

\layout {
    indent = 3.0\cm
short-indent = 1.5\cm
    \context { \GrandStaff \accepts "Lyrics" }
}
% uncomment to enable generating midi file from the lilypond source
%     \midi {
%     } 
} % score
